name: Build Images

on:
  push:
    branches:
      - main
  pull_request:
#    branches:
#      - main

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install make
        run: sudo apt-get install -y make

      - name: Install prereqs
        run: sudo make prereqs

      - name: Run make
        env:
          ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}
        run: make encrypt -j $(nproc)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: images
          path: encrypted/*.raw

      - name: Setup AWS CLI
        run: |
          mkdir -p ~/.aws
          cat << EOF > ~/.aws/credentials
          [default] 
          aws_access_key_id = ${{ secrets.ACCESS_KEY }}
          aws_secret_access_key = ${{ secrets.SECRET_KEY }}
          EOF

      - name: Upload to S3
        run: |
          aws s3 cp s3://sysext/dev/latest latest --endpoint-url ${{ secrets.S3_URL }}
          latest=$(($(cat latest) + 1))
          echo ${latest} > latest
          aws s3 cp latest s3://sysext/dev/latest --endpoint-url ${{ secrets.S3_URL }}
          for file in $(ls encrypted/)
          do
            aws s3 cp encrypted/${file} s3://sysext/dev/${file%.raw}_${latest}.raw --endpoint-url ${{ secrets.S3_URL }}
          done
          