name: Build Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install make
        run: sudo apt-get install -y make

      - name: Install prereqs
        run: sudo make preqreqs

      - name: Run make
        run: make output -j $(nproc)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: images
          path: output/*.erofs
